"""Application boundaries. Implementations belong to infrastructure."""

from typing import Protocol, Any

Record = dict[str, Any]


class AuthRepository(Protocol):
    def user(self, user_id: int, lock=False) -> Record: ...
    def lock_administration(self): ...
    def find_user(self, **filters) -> Record | None: ...
    def save_user(self, data: Record, user_id: int | None = None) -> Record: ...
    def users(self) -> list[Record]: ...
    def roles(self) -> list[Record]: ...
    def role(self, role_id: int) -> Record: ...
    def permissions(self) -> list[Record]: ...
    def save_role(self, data: Record, role_id: int | None = None) -> Record: ...
    def audit(self, action: str, actor_id=None, target_id=None, details=None): ...
    def events(self, action=None) -> list[Record]: ...


class CatalogRepository(Protocol):
    def categories(self) -> list[Record]: ...
    def category(self, category_id: int) -> Record: ...
    def save_category(self, data: Record, category_id=None) -> Record: ...
    def product(self, product_id: int) -> Record: ...
    def products(self, **filters) -> Record: ...
    def save_product(self, data: Record, product_id=None) -> Record: ...
    def change_price(self, product_id, amount, version, actor_id) -> Record: ...
    def history(self, product_id: int) -> list[Record]: ...
    def add_history(self, product_id, previous, amount, version, actor_id): ...
    def events(self) -> list[Record]: ...
    def audit(self, action, actor_id, entity_type, entity_id, details=None): ...
    def replace_image(self, product_id, reference, actor_id): ...


class OrdersRepository(Protocol):
    def tables(self) -> list[Record]: ...
    def table(self, table_id, lock=False) -> Record: ...
    def save_table(self, data, table_id=None) -> Record: ...
    def delete_table(self, table_id) -> Record: ...
    def get_session(self, session_id, lock=False) -> Record: ...
    def active_session(self, table_id) -> Record | None: ...
    def save_session(self, data, session_id=None) -> Record: ...
    def orders(self, session_id=None) -> list[Record]: ...
    def order(self, order_id, lock=False) -> Record: ...
    def save_order(self, data, lines=None, order_id=None) -> Record: ...
    def cancel(self, order_id, reason, actor_id): ...


class UnitOfWork(Protocol):
    auth: AuthRepository
    catalog: CatalogRepository
    orders: OrdersRepository

    def commit(self): ...
    def rollback(self): ...


class Security(Protocol):
    def hash_password(self, value): ...
    def verify(self, hashed, value): ...
    def tokens(self, user): ...
    def decode(self, token, kind): ...
    def reset_token(self): ...
    def hash_token(self, token): ...
    def send_reset(self, recipient, token): ...
